workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.pappostudios.milometry"

    triggering:
      events:
        - push
      branch:
        include:
          - main

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build Flutter for iOS
        script: |
          flutter build ios \
            --debug \
            --flavor ios-production \
            -t lib/main_prod.dart

      - name: Build Flutter for Android
        script: |
          flutter build appbundle \
            --debug \
            --flavor android-production \
            -t lib/main_prod.dart

    artifacts:
      - build/ios/iphoneos/*.app
      - build/app/outputs/bundle/androidProductionRelease/app-android-production-release.aab

    integrations:
      app_store_connect: $APP_STORE_CONNECT_API_KEY

    publishing:
      app_store_connect:
        bundle_id: com.pappostudios.milometry
        ipa_location: build/ios/iphoneos/Runner.ipa